name: Build RSS feeds

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build RSS
        run: npm run build:feeds
        env:
          # Se o site NÃO for user/organization page, ajuste a URL base aqui:
          # SITE_URL: https://<owner>.github.io/<repo>
          REPO_OWNER: ${{ github.repository_owner }}

      - name: Commit feeds
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add rss-pt.xml rss-en.xml
            git commit -m "chore: update RSS feeds"
            git push
          else
            echo "No changes"
          fi
